version: "3.9"

services:
  dae:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility